version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}-{{ .Branch }}
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}-{{ .Branch }}

      - run: yarn lint

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker build -t $DOCKER_IMAGE:$CIRCLE_TAG .
          docker tag $DOCKER_IMAGE:$CIRCLE_TAG $DOCKER_IMAGE:stable
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_IMAGE:$CIRCLE_TAG
          docker push $DOCKER_IMAGE:stable

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          context: global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
